### PR TITLE
Add two auxiliary files

### PR DESCRIPTION
**Pull request by lipeng31**
Add requirements file for pip and a python script to generate the file specified by config.dev_cv_csv_path.

### CODE REVIEW

**Comment by qiuqiangkong** [comment]
Dear Li,


    Many thanks for your commits!


    Please could you explain in brief why the updates are necessary? It seems like hdf5 is  abandoned? What is the 1000 files, the training or testing?


    Many thanks!


Best wishes,


Qiuqiang

________________________________

**Comment by lipeng31** [comment]
Hi Qiuqing. The related code is aimed to relieve the out of memory problem in the `pack_features` function, where the original implementation loads all the features into memory before packing and store them to a file, thus causes OOM when the training data is big.
Thanks.

**Comment by qiuqiangkong** [comment]
Hi  Li,


    OK, many thanks!


Best wishes,


Qiuqiang

________________________________

**Comment by qiuqiangkong** [comment]
Hi Yong,


FYI


Qiuqiang

________________________________

**Pull request closed without merging**
